DROP DATABASE IF EXISTS ph22_kadai05_pw51a335_02;
SET sql_mode='STRICT_ALL_TABLES';
CREATE DATABASE ph22_kadai05_pw51a335_02;

USE ph22_kadai05_pw51a335_02

DROP TABLE IF EXISTS accounts;
CREATE TABLE accounts(
	id INT AUTO_INCREMENT PRIMARY KEY,
	login_id VARCHAR(10) NOT NULL UNIQUE,
	password_hash VARCHAR(255) NOT NULL,
	name VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS image_file;
CREATE TABLE image_file(
	id INT AUTO_INCREMENT PRIMARY KEY,
	account_id INT NOT NULL,
	title VARCHAR(127) NOT NULL,
	filename VARCHAR(127) NOT NULL UNIQUE,
	publish INT DEFAULT 0
);